const heading = document.getElementById("heading")
const longitudeInput = document.getElementById("longitudeInput")
const latitudeInput = document.getElementById("latitudeInput")
const SubmitInputBtn = document.getElementById("inputBtn")
const latitude = document.getElementById("latitude")
const longitude = document.getElementById("longitude")
const temprature = document.getElementById("temprature")
const windSpeed = document.getElementById("windSpeed")
const rain = document.getElementById("rain")
const dayAurNight = document.getElementById("dayAurNight")

